### ISSUE TITLE
Devendor catch.hpp

### ISSUE THREAD

**Issue by jayvdb** [py2many/py2many#193]
catch.hpp in https://github.com/adsharma/py2many/tree/main/py14/runtime should be replaced with https://github.com/catchorg/Catch2

It is under the Boost license, similar to MIT, but including it in this repo means advertising multiple licenses, and attributions.

**Comment by jayvdb** [comment]
https://github.com/nemequ/portable-snippets/tree/master/check uses a slightly more permissive license, CC0, and also looks to be a lot smaller for just this, but also comes as part of a larger collection of re-usable snippets that we could probably benefit from, and a sister project https://nemequ.github.io/hedley/ which would make the generated output more portable.

**Comment by adsharma** [comment]
pycpp/runtime/catch.hpp is already under the boost software license. So by updating it to catch2, we don't make it any better or worse license wise. But we do have to say parts of the  runtime may be covered by other licenses.

I think we need to advertise licenses for only things included in this git repo. If our setup scripts are pulling from other repos with different licenses, that's a situation our users are likely to be already familiar with. I can imagine different language ecosystems using different licenses for their tools and runtime.
