### ISSUE TITLE
PyPI name conflicts

### ISSUE THREAD

**Issue by jayvdb** [py2many/py2many#238]
The rename of py14 -> pycpp creates a new conflict with https://pypi.org/project/PyCPP/ -> https://github.com/commander07/PyCPP .

We also have conflicts with other packages.
- https://pypi.org/project/pykt/
- https://pypi.org/project/pygo/
- https://pypi.org/project/pynim/
- https://pypi.org/project/pydart/

If we added JavaScript support, we would conflict with https://pypi.org/project/pyjs/ ; likewise https://pypi.org/project/pyjava/

None of those are highly popular packages, but we will need to start planning how to avoid these conflicts.

It is possible to leave these directories as-is in this project, and use setup.py to remap them under the `py2many` directory.

**Comment by adsharma** [comment]
As long as we import `py2many.pycpp` or use relative imports, we should be safe. The main conflict scenario is if we have code like:

from pycpp import xyz

We do have some of this. I'm inclined to leave the directories as-is.

**Comment by jayvdb** [comment]
Ugh!  `pysmt` is the *main* python library for smt: https://github.com/pysmt/pysmt

The problem is not our imports - it is that someone can not install py2many and https://pypi.org/project/PySMT/ at the same time.  They will overwrite each other in Python's `site-packages` directory.
