### ISSUE TITLE
Windows CI doesnt invoke Julia and Kotlin formatters

### ISSUE THREAD

**Issue by jayvdb** [py2many/py2many#339]
Recently discussed at https://github.com/adsharma/py2many/pull/336#discussion_r659010567

This is why `test_self_transpile.py` allows `FileNotFoundError` for Kotlin and Julia.

**Comment by div72** [comment]
> And I suspect that the newly added V and smt also dont support Windows

Is there any Windows specific checks for py2many? V should work fine otherwise.

**Comment by jayvdb** [comment]
https://github.com/domluna/JuliaFormatter.jl/pull/599 and https://github.com/pinterest/ktlint/issues/1363 look like good solutions which would avoid needing to build weird hacks for CI.

**Comment by jayvdb** [comment]
SMT and Kotlin have been addressed by using jgo.

More broadly SMT is covered by https://github.com/py2many/py2many/issues/568

I believe the Julia issues have also been resolved by https://github.com/py2many/py2many/pull/479

There are no Windows specific code in py2many, but there are definitely some specific Vlang specified problems being avoided by `_suppress_exceptions=(AstNotImplementedError, AstUnrecognisedBinOp),` at https://github.com/py2many/py2many/blob/c12df6a/tests/test_transpile_self.py#L254 , but a specified issue about that is worth creating and tackling but is not this issue.

https://github.com/py2many/py2many/pull/569 removes the workarounds which were put in place that creates this issue, so this can be closed if that succeeds.
