### ISSUE TITLE
FileNotFoundError [Errno 2] No such file or directory: 'format.jl

### ISSUE THREAD

**Issue by ankushsoni96** [py2many/py2many#456]
I am unable to execute the Julia conversion code. I am getting the following error:

```Error: Could not format: try.jl```
```Due to: FileNotFoundError [Errno 2] No such file or directory: 'format.jl' ```

Here, try.py is the file I want to convert to Julia (It is in the same directory)

**Comment by div72** [comment]
Try: `julia -e 'using Pkg; Pkg.add("JuliaFormatter")'`.

**Comment by ankushsoni96** [comment]
It didn't work. The error remains the same for CPP as well. Refer the attached screenshot
![Screenshot from 2022-02-03 12-11-12](https://user-images.githubusercontent.com/19350966/152293845-34f0ca06-6710-4e7d-82cb-fead163baa70.png)

**Comment by div72** [comment]
@ankushsoni96 For C++ you need to install clang-format, assuming you are on Ubuntu `sudo apt install clang-format` should work by itself.

For Julia, you need to add the formatter to your PATH; so that py2many can find it. It should be somewhere in `~/.julia`.

**Comment by ankushsoni96** [comment]
I am unable to locate formatter. There are multiple directories by the name 'julia' but 'formatter' doesn't exist in any of them. :(

**Comment by adsharma** [comment]
https://github.com/adsharma/py2many/blob/main/docker/Dockerfile - has the
recipe for setting up your environment for archlinux. The last few lines
are relevant to your question.
