### ISSUE TITLE
py2many.exceptions.AstUnrecognisedBinOp: Union[Union[int,Union[str,int]],Union[str,int]] <class 'ast.Sub'> int Error

### ISSUE THREAD

**Issue by HorridModz** [py2many/py2many#523]
Hi, thanks for this awesome python transpiler! I am very excited to use this. I did find a couple bugs in it, which were expected.

Here is the issue I got:

```
Writing to: .
Code.py ... Code.cpp
Code.py:680:14: py2many.exceptions.AstUnrecognisedBinOp: Union[Union[int,Union[str,int]],Union[str,int]] <class 'ast.Sub'> int
Error: Could not format: Code.cpp
```

I was getting the error in this line of code:
`startpos = indexofstr(startstr,fullstr,casesensitive) + 1`
Changing the code to this fixed the issue:
`startpos = indexofstr(startstr,fullstr,casesensitive)`

I am assuming that the transpiler does not recognize I am trying to use the return of the function for path.
To double-check, I tested this concept in c++ (what I was compiling to) and it worked:

`#include <iostream>

int a(int a1,int a2,int a3){
    return (a1 + a2 + a3);
}

int b(){
    int c;
    c = a(1,2,3) + 1;
    return c;
}

int main(){
    std::cout << b();
    return 0;
}`

It would be awesome if this issue could be fixed! For now, I will have to work around it.

**Comment by div72** [comment]
Could you provide the Python source? It'd be hard to track it down otherwise. Also did you try type annotating the return yourself?

**Comment by HorridModz** [comment]
> Could you provide the Python source? It'd be hard to track it down otherwise. Also did you try type annotating the return yourself?

My code is not pythonic as I'm a beginner, so you may cringe. But if you insist, here it is:
[PythonCode.txt](https://github.com/py2many/py2many/files/9237522/PythonCode.txt)

**Comment by HorridModz** [comment]
> Could you provide the Python source? It'd be hard to track it down otherwise. Also did you try type annotating the return yourself?

I will try type annotating right now!

Awesome, this updated code worked:
`startpos = int(indexofstr(startstr,fullstr,casesensitive)) + 1`

Maybe detection of this could be implemented? Either way, thanks a lot!

**Comment by div72** [comment]
That should also work, but what I mean by type annotating is this:

```python
def indexofstr(substr: str, fullstr: str, casesensitive: bool = True, backward: bool = False) -> int:
```

See https://peps.python.org/pep-0484/ for more details.

**Comment by HorridModz** [comment]
> That should also work, but what I mean by type annotating is this:
> 
> ```python
> def indexofstr(substr: str, fullstr: str, casesensitive: bool = True, backward: bool = False) -> int:
> ```
> 
> See https://peps.python.org/pep-0484/ for more details.

Oh, my bad. I am self-taught and a newbie. I assumed type annotation meant explicitly declaring the type.
Thanks a lot for linking a guide so I can learn about it!

**Comment by jayvdb** [comment]
Was there something here that py2many could have done better?

If not, can this issue be closed?

**Comment by HorridModz** [comment]
> Was there something here that py2many could have done better?
> 
> If not, can this issue be closed?

The code wasn't using type hinting. Since it's impossible to detect types, py2many should require type hints.
