### ISSUE TITLE
Class Type Assumptions (expected str instance, NoneType found)

### ISSUE THREAD

**Issue by HorridModz** [py2many/py2many#525]
There is probably something going on that I do not understand, or maybe my code is not pythonic. But I am getting an error with this code:

class timemanager:
    rawtime = getrawtime
    formattime = formattime
    gettime = gettime
    sleepseconds = sleepseconds
    wait = waitseconds
    waitmili = waitmili
    waitseconds = waitseconds
    sleep = sleepseconds
    sleepmili = sleepmili
    sleepseconds = sleepseconds
    startspeedtest = startspeedtest
    endspeedtest = endspeedtest

This is a class simply to make naming easier - EX: Instead of typing `getrawtime()`, I can organize my code by typing  `time.rawtime()` with this class.
The c++ transpiler does not like this - I got this error:

Writing to: .
Code.py ... Code.cpp
Code.py:1370:0: py2many.exceptions.AstNotImplementedError: sequence item 15: expected str instance, NoneType found
Error: Could not format: Code.cpp
Due to: FileNotFoundError [WinError 2] The system cannot find the file specified

I was expecting classes to be given a type automatically, as this would fix the error, while still making your code make sense and work the same.
But I am probably missing something. I am not at allfamiliar with OOP or classes.

**Comment by div72** [comment]
I cannot reproduce, could you give the whole script?

Also instead of aliasing the function, it'd be much more pythonic and much likely to be correctly transpiled if you defined the functions inside the class. Although I'm also not sure on how complete the time to chrono conversion for the C++ backend.

**Comment by HorridModz** [comment]
> I cannot reproduce, could you give the whole script?
> 
> Also instead of aliasing the function, it'd be much more pythonic and much likely to be correctly transpiled if you defined the functions inside the class. Although I'm also not sure on how complete the time to chrono conversion for the C++ backend.

Nevermind... it was just a newbie thing I did to embarass myself. I also didn't understand the error correctly, and that section of code wasn't what was causing it. I get what I did now.
