### ISSUE TITLE
Split CI to only run individual language tests

### ISSUE THREAD

**Issue by jayvdb** [py2many/py2many#540]
Now that py2many/cli.py has been split up in https://github.com/py2many/py2many/pull/511 , we can split the CI so that if a change only needed to change `pyjl/` , only the Julia tests should run, speeding up PR CI.

**Comment by jayvdb** [comment]
If there is a change to `py2many/` , a full build is still needed to determine the effects on all transpilers.

["paths-ignore"](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths) can be used to skip the full CI if the PR only includes changes to a single transpiler

**Comment by adsharma** [comment]
Done. We now have a drop down to select platforms and languages to run.
