### ISSUE TITLE
py2many.exceptions.AstUnrecognisedBinOp translating python script

### ISSUE THREAD

**Issue by JalonSolov** [py2many/py2many#552]
1. Clone https://github.com/elliotchance/vsql
2. cd vsql
```
[jalon@7950x vsql]$ ../py2many/py2many.py --v=1 generate-grammar.py
Writing to: .
generate-grammar.py ... generate-grammar.v
generate-grammar.py:136:14: py2many.exceptions.AstUnrecognisedBinOp: str <class 'ast.Mult'> int
Error: ['v', 'fmt', '-w', 'generate-grammar.v'] (code: 1):
b'generate-grammar.v:1:1: error: `FAILED` evaluated but not used\n    1 | FAILED\n      | ~~~~~~\n\nInternal vfmt error while formatting file: generate-grammar.v.\nEncountered a total of: 1 errors.\n'b''
[jalon@7950x vsql]$ ls
bench.vsql  cmd         docs      generate-grammar.py  grammar.bnf  Makefile   readthedocs.yaml  test_concurrent_writes.vsql  v.mod
bin         Dockerfile  examples  generate-grammar.v   LICENSE      README.md  scripts           tests                        vsql
[jalon@7950x vsql]$ cat generate-grammar.v
FAILED[jalon@7950x vsql]$
```

**Comment by JalonSolov** [comment]
Only tried with v originally, then decided to try translating to other langs... same error.  So it's not the output type that matters, only the contents of the python script being translated.

**Comment by div72** [comment]
@JalonSolov Only the Dart backend seems to support string multiplication from what I can see from `tests/test_unsupported.py:204`. I've created a PR to add support for the V backend but that file needs some work before it could be transpiled. (file needs some type annotations, object subclass is redundant now, backends will still stumble on something like lambdas)

**Comment by JalonSolov** [comment]
V should be fairly easy to support for that - turn it into a `.repeat()` call.

I tried with Go and Nim and got the same error, but it appeared to work with Rust.  At least it generated a file with no error messages.

**Comment by div72** [comment]
> V should be fairly easy to support for that - turn it into a `.repeat()` call.

See #553.

> I tried with Go and Nim and got the same error, but it appeared to work with Rust. At least it generated a file with no error messages.

I'm surprised, does the generated file actually work?
