### ISSUE TITLE
Flutter pinned to 2.10.5

### ISSUE THREAD

**Issue by jayvdb** [py2many/py2many#586]
Since https://github.com/py2many/py2many/pull/468 , flutter has been pinned to v2.10.5 .

The primary reason for this is the `vnum` package is unmaintained.  c.f. https://github.com/py2many/py2many/issues/467 and https://github.com/AmirKamali/Flutter_Vnum/issues/7

Current flutter version is 3.16.2.

This means most people wont be able to install the correct version locally, and the tests fail if they have dart/flutter installed.

**Comment by adsharma** [comment]
Fixed by recent commits. We no longer use vnum
