### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by mwichmann** [py2many/py2many#595]
After installing from PyPI in a virtualenv even simple operations (`py2many --help`) lead to:
```
Traceback (most recent call last):
...
ModuleNotFoundError: No module named 'distutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
ModuleNotFoundError: No module named 'pycpp'
```

**Comment by mwichmann** [comment]
Guess I should b more clear... distutils is gone as of 3.12, so it *can't* be installed.

**Comment by adsharma** [comment]
We need to make a new release. Should be fixed in main.

The only reference to `distutils` is in `setup.py`. I just updated README so people don't try to run it directly.

**Comment by adsharma** [comment]
Also see: https://github.com/py2many/py2many/pull/597
CI is passing with 3.12 for rust

**Comment by adsharma** [comment]
Made a new release and tested this flow. 
Please reopen if you still see this.
