### ISSUE TITLE
Q: basic py2many.pyd work at language/syntax level in my dlang fork now. @adsharma Will you accept as it is for now?

### ISSUE THREAD

**Issue by mw66** [py2many/py2many#603]
basic py2many.pyd work at language/syntax level in my dlang fork now. @adsharma  Will you accept as it is for now?

If you do, I will create a PR; otherwise, I will wait.

https://forum.dlang.org/post/jrozknhxpdmgeioqobbi@forum.dlang.org

Hi,

I have made basic py2many.pyd work at language/syntax level in my dlang fork:

https://github.com/mw66/py2many/tree/dlang

The following examples works now:

https://github.com/mw66/py2many/tree/dlang/tests/expected

py2many/ 13:56:23$ ls ./tests/expected/*.d
./tests/expected/bubble_sort.d
./tests/expected/cls.d
./tests/expected/fib.d
./tests/expected/import_tests.d
./tests/expected/classes.d
./tests/expected/dict.d
./tests/expected/hello_world.d
./tests/expected/nested_dict.d

Please use this Makefile for local setup and run tests:

https://github.com/mw66/py2many/blob/dlang/Makefile

I haven't created PR to be merged into the main branch, since it's better to pass all the tests.

The remaining work is to make Python's specific feature (e.g. async), library (e.g. complex number, NamedTemporaryFile) work in D. There are many things need to be done, if you have time, you can pick up from my fork, and work from there. (E.g. you can create PR to my branch, and when everything is ready, we submit to the main py2many all together).

The more people can help, the faster we can get this done.

HTH.

**Comment by adsharma** [comment]
> I haven't created PR to be merged into the main branch, since it's better to pass all the tests.

Please create a PR. Not all languages pass all the tests. The test harness takes the absence of a expected output as a hint to skip the tests.

I'd replace the Makefile with a workflow using pytest or tox like other languages do. 

```
pytest -k dlang --setup-plan
```

Also please update `docker/Dockerfile` with some hints on how to setup a dev environment.

Lastly, for some CI/CD test coverage, you'll need to update `.github/workflow/main.yaml`  (ok with a separate PR)

**Comment by mw66** [comment]
https://github.com/py2many/py2many/pull/606

Made more tests passing; removed Makefile.
